### ISSUE TITLE
How to set it up?

### ISSUE THREAD

**Issue by m1ndgames** [mdtrooper/RealTimeBattle_reloaded#1]
Hey!
1st let me says that i really love the idea of bringing rtb back to live again!

But i struggle hard to compile the source, can you help?

edit: i realized that its not compile-able yet. Is there anything that can be done to support you?
(I speak only Perl/Bash) :/)

**Comment by mdtrooper** [comment]
Hi, thanks.

Well, it is works with cmake, only do for the old realtimebattle:

```
git clone https://github.com/mdtrooper/RealTimeBattle_reloaded.git
cd RealtimeBattle/original_gtk
cmake .
make
```

Bye.

**Comment by m1ndgames** [comment]
Cool thanks!
I helped myself by setting up a dedicated rtb vm. (you can still get it for debian wheezy, and i had to isolize it anyway: https://rtb.m1nd.io/)

Additionally, i advertized this project on the codingame forums: https://forum.codingame.com/t/realtimebattle-reloaded/2790/1
